import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import LoaderButton from '../components/loaders/LoaderButton'
const Home: NextPage = () => {
  return (
    <div className='h-screen w-screen flex justify-center items-center bg-slate-200'>
      <Head>
        <title>Tele Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
    </div>
  )
}

export default Home
