import React from 'react';
import Image from 'next/image'
import Head from 'next/head'
import { NextPage } from 'next';
import { motion } from 'framer-motion';
import EmailGrabber from '../components/LoginPage/EmailGrabber';
const LoginPage:NextPage = () => {
    const handleSubmit = () => {

    }
    return (
        <div className='h-screen w-screen flex justify-center items-center bg-slate-200'>
        <Head>
            <title>Tele Cloud</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.svg" />
        </Head>
            <form className='flex items-center flex-col w-full h-full justify-center bg-white md:w-fit md:h-fit md:px-10 md:py-14 md:border md:border-gray-300 md:shadow-xl md:rounded-lg'>
                <div className='flex items-center justify-center gap-5 mb-10 overflow-hidden'>
                    <Image src="/favicon.svg" alt='T Icon' width={50} height={50} />
                    <motion.h1
                        initial={{y: 50}}
                        animate={{y:0}}
                        transition={{duration:0.2,ease:"easeOut",delay:0.5}}
                        className='text-5xl font-bold text-gray-700'>Tele Cloud</motion.h1>
                </div>
                <EmailGrabber handleSubmit={handleSubmit}/>
            </form>
        </div>
    );
};

export default LoginPage;
